# Generated by Django 4.2.25 on 2025-11-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_text', models.TextField()),
                ('last_bot_responses', models.JSONField(default=dict)),
                ('retrieved_results', models.JSONField(default=dict)),
                ('similarity_threshold_used', models.FloatField(default=0.8)),
                ('chat_history', models.JSONField(default=dict)),
                ('assigned_to', models.CharField(default='Tech Support', max_length=100)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_tickets',
            },
        ),
        migrations.DeleteModel(
            name='RegisteredTicket',
        ),
    ]
